config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    resources :comments do
      resources :subcomments
    end
  end
  root "posts#index"

  get '/about', to: 'pages#about'
  get '/avatar', to: 'pages#avatar'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  has_many :subcomments
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :user
  validates :title, presence: true, length: {minimum: 5}
  validates :body, presence: true
end

app/models/subcomment.rb
class Subcomment < ApplicationRecord
  belongs_to :comment
end

app/models/user.rb
class User < ApplicationRecord
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:comment_id])
    @comment = @post.comments.create(params[:comment].permit(:name, :body))

    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:comment_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    redirect_to post_path(@post)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about

  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @posts = Post.all
  end
  def new
    @post = current_user.posts.build
  end

  def create

    @post = current_user.posts.build(post_params)
    if @post.save
    redirect_to @post
    else
      render 'new'
    end

  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(params[:post].permit(:title,:body))
      redirect_to @post
    else
      render 'edit'
    end
  end
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to root_path
  end

  private
  def post_params
    params.require(:post).permit(:title,:body)
  end
end

app/controllers/subcomments_controller.rb
class SubcommentsController < ApplicationController
  def create
    @post = Post.find(params[:comment_id])
    @comment = @post.comments.find(params[:comment_id])
    @subcomment = @comment.subcomments.create(params[:subcomment], permit(:name, :body))

    redirect_to post_path(@post)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def new
    @user = User.create
  end
  def create
    @user = User.create( user_params )
  end

  private

# Use strong_parameters for attribute whitelisting
# Be sure to update your create() and update() controller methods.

  def user_params
    params.require(:user).permit(:avatar)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/subcomments_helper.rb
module SubcommentsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
  <div class="comment_content">
    <p class="comment_name"><Strong><%= comment.name %></Strong></p>
    <p class="comment_body"><%= comment.body %></p>
    <p class="comment_time"><%= time_ago_in_words(comment.created_at) %></p>
  </div>
  <% if user_signed_in? %>
      <p><%= link_to 'Delete', [comment.post, comment],
                    method: :delete,
                    class: "button",
                    data: { confirm: 'Are you sure?'} %>
      </p>
  <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for ([@post, @post.comments.build]) do |f| %>
    <p>
      <%= f.label :name %> <br>
      <%= f.text_field :name %>
    </p>

    <p>
      <%= f.label :body %> <br>
      <%= f.text_area :body %>
    </p>
    <br>
    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<body>
<div id="sidebar">
  <div id="logo">
    <%= link_to root_path do %>
        <%= image_tag "logo.svg" %>
    <% end %>
  </div>

  <ul>
    <li class="category">Buttons</li>
    <li><%= link_to "Blog", root_path %></li>
    <li><%= link_to "New Post", new_post_path %></li>
    <li><%= link_to "About", about_path %></li>
    <% if user_signed_in? %>
    <li><%= link_to "Setup Avatar", avatar_path %></li>
    <% end %>
  </ul>

  <ul>
    <li class="category">My links</li>
    <li><a href="https://new.vk.com/zoombuone">VK</a></li>
    <li><a href="https://github.com/ZoOmbu">GitHub</a></li>
    <li></li>
    <li></li>
  </ul>
    <% if user_signed_in? %>
      <p class="sign_in"><%= link_to "Log Out",
                                       destroy_user_session_path,
                                       method: :delete,
                                       data: { confirm: 'Are you sure to log out?' } %></p>
      <% else %>
  <p class="sign_in"><%= link_to "Log in", user_session_path %></p>
    <% end %>
</div>

<div id="main_content">
  <div id="header">
    <% if current_page?(root_path) %>
        <p>All Posts</p>
  <% elsif current_page?(about_path) %>
        <p>About</p>
  <% else %>
        <%= link_to "Back to All Posts", root_path, class: "button" %>
  <% end %>

        <div class="buttons">
          <% if user_signed_in? %>
              <p class="link">Logged as: <%= current_user.email %></p>
          <% else %>
              <p class="link">Please Login to write posts </p>
          <% end %>
    </div>

  </div>
  <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert") %>
  <% end %>
  <%= yield %>

</div>




</body>

  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">
  <div id="profile_image">
    <%= image_tag "profile.jpeg" %>
  </div>

  <div id="content">
    <h1>I'm Valeriy Bondarenko</h1>
    <p>This is my blog site for Applikey Solutions.</p>
    <p>I am trying to do my best :)</p>
  </div>
</div>

app/views/pages/avatar.html.erb
<div id="page_wrapper">
  <div id="profile_image">
    <%= image_tag @user.avatar.url(:medium) %>
  </div>

  <div id="content">
    <h1>Preview of avatar</h1>
  </div>
</div>
<%= form_for @user, url: user_session_path, html: { multipart: true } do |form| %>
    <%= form.file_field :avatar %>

    <p>
      <%= form.submit %>
    </p>
<% end %>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
    <% if @post.errors.any? %>
        <div id="errors">
          <h2><%= pluralize(@post.errors.count, "error") %> prevented from saving the post</h2>
          <ul>
            <% @post.errors.full_messages.each do |msg| %>
                <li> <%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>
    <p>
      <%= f.label :body %><br>
      <%= f.text_area :body %>
    </p>

    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">
  <h1> Edit post</h1>

  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
    <% @posts.each do |post| %>
        <div class="post_wrapper">
          <h2 class="title"><%= link_to post.title, post %></h2>
          <h3 class="title"><%= post.user.email %></h3>
          <p class="date"><%= post.created_at.strftime("%B, %d, %Y") %></p>
        </div>
    <% end %>

app/views/posts/new.html.erb
<div id="page_wrapper">
    <h1> New post</h1>

   <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div id="post_content">
     <h1 class="title">
       <%= @post.title %>
     </h1>

     <p class="date">
       Submitted <%= time_ago_in_words(@post.created_at) %> Ago
       <% if @post.user == current_user %>
        <%= link_to 'Edit', edit_post_path(@post), class: "button" %>
        <%= link_to 'Delete', post_path(@post),
                 method: :delete,
                 class: "button",
                 data: { confirm: 'Are you sure?'} %>
       <% end %>
     </p>

     <p class="body">
       <%= @post.body %>
     </p>
  <div id="comments">
    <h2> <%= @post.comments.count %> Comments</h2>
    <%= render @post.comments %>

    <h3>Add a comment</h3>
    <%= render "comments/form" %>
  </div>
</div>

app/views/subcomments/_form.html.erb
<%= form_for ([@comment, @comment.subcomments.build]) do |f| %>
    <p>
      <%= f.label :name %> <br>
      <%= f.text_field :name %>
    </p>

    <p>
      <%= f.label :body %> <br>
      <%= f.text_area :body %>
    </p>
    <br>
    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/subcomments/_subcomment.html.erb
<div class="comment clearfix">
  <div class="comment_content">
    <p class="comment_name"><Strong><%= subcomment.name %></Strong></p>
    <p class="comment_body"><%= subcomment.body %></p>
    <p class="comment_time"><%= time_ago_in_words(subcomment.created_at) %></p>
  </div>
  <% if user_signed_in? %>
      <p><%= link_to 'Delete', [subcomment.comment.post, subcomment],
                     method: :delete,
                     class: "button",
                     data: { confirm: 'Are you sure?'} %>
      </p>
  <% end %>
</div>